In [3]:
# Step 1 - Load Data
import pandas as pd
dataset = pd.read_csv("Social_Network_Ads.csv")
X = dataset.iloc[:,1:4].values
y = dataset.iloc[:, -1].values

In [4]:
print X

[['Male' 19L 19000L]
 ['Male' 35L 20000L]
 ['Female' 26L 43000L]
 ...
 ['Female' 50L 20000L]
 ['Male' 36L 33000L]
 ['Female' 49L 36000L]]


In [5]:
print y

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [6]:
# Step 2 - Convert Gender to number
from sklearn.preprocessing import LabelEncoder
labelEncoder_gender =  LabelEncoder()
X[:,0] = labelEncoder_gender.fit_transform(X[:,0])

# Optional - if you want to convert X to float data type
import numpy as np
#X = np.vstack(X[:, :]).astype(np.float)

In [7]:
X

array([[1, 19L, 19000L],
       [1, 35L, 20000L],
       [0, 26L, 43000L],
       ...,
       [0, 50L, 20000L],
       [1, 36L, 33000L],
       [0, 49L, 36000L]], dtype=object)

In [8]:
# Step 3 - Split into Train and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [9]:
print X_train
print y_train

[[0 44L 39000L]
 [1 32L 120000L]
 [0 38L 50000L]
 [0 32L 135000L]
 [0 52L 21000L]
 [0 53L 104000L]
 [1 39L 42000L]
 [1 38L 61000L]
 [0 36L 50000L]
 [0 36L 63000L]
 [0 35L 25000L]
 [1 35L 50000L]
 [1 42L 73000L]
 [0 47L 49000L]
 [0 59L 29000L]
 [1 49L 65000L]
 [0 45L 131000L]
 [0 31L 89000L]
 [0 46L 82000L]
 [0 47L 51000L]
 [1 26L 15000L]
 [1 60L 102000L]
 [0 38L 112000L]
 [1 40L 107000L]
 [0 42L 53000L]
 [1 35L 59000L]
 [1 48L 41000L]
 [0 48L 134000L]
 [0 38L 113000L]
 [1 29L 148000L]
 [0 26L 15000L]
 [1 60L 42000L]
 [1 24L 19000L]
 [1 42L 149000L]
 [0 46L 96000L]
 [1 28L 59000L]
 [1 39L 96000L]
 [1 28L 89000L]
 [1 41L 72000L]
 [1 45L 26000L]
 [0 33L 69000L]
 [0 20L 82000L]
 [1 31L 74000L]
 [1 42L 80000L]
 [0 35L 72000L]
 [0 33L 149000L]
 [1 40L 71000L]
 [0 51L 146000L]
 [1 46L 79000L]
 [1 35L 75000L]
 [1 38L 51000L]
 [0 36L 75000L]
 [0 37L 78000L]
 [1 38L 61000L]
 [0 60L 108000L]
 [0 20L 82000L]
 [1 57L 74000L]
 [1 42L 65000L]
 [1 26L 80000L]
 [1 46L 117000L]
 [1 35L 61000L]
 [0 21L 6

In [10]:
# Step 4 - Feature Scaling
from sklearn.preprocessing import StandardScaler
ss_X = StandardScaler()
X_train = ss_X.fit_transform(X_train)
X_test = ss_X.transform(X_test)

C:\Users\ADMIN\Anaconda2\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [11]:
X_train

array([[-0.98019606,  0.58164944, -0.88670699],
       [ 1.02020406, -0.60673761,  1.46173768],
       [-0.98019606, -0.01254409, -0.5677824 ],
       [-0.98019606, -0.60673761,  1.89663484],
       [-0.98019606,  1.37390747, -1.40858358],
       [-0.98019606,  1.47293972,  0.99784738],
       [ 1.02020406,  0.08648817, -0.79972756],
       [ 1.02020406, -0.01254409, -0.24885782],
       [-0.98019606, -0.21060859, -0.5677824 ],
       [-0.98019606, -0.21060859, -0.19087153],
       [-0.98019606, -0.30964085, -1.29261101],
       [ 1.02020406, -0.30964085, -0.5677824 ],
       [ 1.02020406,  0.38358493,  0.09905991],
       [-0.98019606,  0.8787462 , -0.59677555],
       [-0.98019606,  2.06713324, -1.17663843],
       [ 1.02020406,  1.07681071, -0.13288524],
       [-0.98019606,  0.68068169,  1.78066227],
       [-0.98019606, -0.70576986,  0.56295021],
       [-0.98019606,  0.77971394,  0.35999821],
       [-0.98019606,  0.8787462 , -0.53878926],
       [ 1.02020406, -1.20093113, -1.582

In [15]:
# Step 5 - Fit SVC Classifier
from sklearn.svm import SVC
classifier = SVC(kernel = "linear", random_state=0)
classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [16]:
# Step 6 - Predict
y_pred = classifier.predict(X_test)

In [17]:
print y_pred

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 1 0 1 1 1 1 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1]


In [18]:
# Step 7 - Confusion Matrix
from sklearn import metrics
cm = metrics.confusion_matrix(y_test, y_pred) 
print(cm)
accuracy = metrics.accuracy_score(y_test, y_pred) 
print("Accuracy score:",accuracy)
precision = metrics.precision_score(y_test, y_pred) 
print("Precision score:",precision)
recall = metrics.recall_score(y_test, y_pred) 
print("Recall score:",recall)

[[66  2]
 [ 9 23]]
('Accuracy score:', 0.89)
('Precision score:', 0.92)
('Recall score:', 0.71875)


In [19]:
# Step 5 - Fit SVC Classifier
from sklearn.svm import SVC
classifier = SVC(kernel = "sigmoid", random_state=0)
classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='sigmoid', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [21]:
# Step 6 - Predict
y_pred = classifier.predict(X_test)
print y_pred

[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 0 0 1 1 1 1 0 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 1 1]


In [22]:
# Step 7 - Confusion Matrix
from sklearn import metrics
cm = metrics.confusion_matrix(y_test, y_pred) 
print(cm)
accuracy = metrics.accuracy_score(y_test, y_pred) 
print("Accuracy score:",accuracy)
precision = metrics.precision_score(y_test, y_pred) 
print("Precision score:",precision)
recall = metrics.recall_score(y_test, y_pred) 
print("Recall score:",recall)

[[63  5]
 [10 22]]
('Accuracy score:', 0.85)
('Precision score:', 0.8148148148148148)
('Recall score:', 0.6875)


In [23]:
# Step 5 - Fit SVC Classifier
from sklearn.svm import SVC
classifier = SVC(kernel = "rbf", random_state=0)
classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [24]:
# Step 6 - Predict
y_pred = classifier.predict(X_test)

In [25]:
# Step 7 - Confusion Matrix
from sklearn import metrics
cm = metrics.confusion_matrix(y_test, y_pred) 
print(cm)
accuracy = metrics.accuracy_score(y_test, y_pred) 
print("Accuracy score:",accuracy)
precision = metrics.precision_score(y_test, y_pred) 
print("Precision score:",precision)
recall = metrics.recall_score(y_test, y_pred) 
print("Recall score:",recall)

[[64  4]
 [ 3 29]]
('Accuracy score:', 0.93)
('Precision score:', 0.8787878787878788)
('Recall score:', 0.90625)
